# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '12.0'

target 'MaDang' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MaDang
  pod 'FirebaseFirestore'
  pod 'FirebaseAuth'  # Authentication을 사용하는 경우


end
